default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: phoenix_rails_development

test:
  <<: *default
  database: phoenix_rails_test

production: &default
  adapter: postgresql
  database: phoenix_rails_production
  password: <%= ENV["POSTGRES_PASSWORD"] %>
